version: '3.5'

services:
  hass-security:
    container_name: hass-security
    image: ghcr.io/analogj/hass-security:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/hass-security/config
      - ./influxdb:/opt/hass-security/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
