#!/command/with-contenv bash

mkdir -p /opt/hass-security/influxdb/

if [ -f "/opt/hass-security/influxdb/config.yaml" ]; then
    echo "influxdb config file already exists. skipping."
else
cat << 'EOF' > /opt/hass-security/influxdb/config.yaml
bolt-path: /opt/hass-security/influxdb/influxd.bolt
engine-path: /opt/hass-security/influxdb/engine
http-bind-address: ":8086"
reporting-disabled: true
EOF
fi

echo "starting influxdb"
influxd run
